package com.mycompany.myapp;


import com.codename1.components.FloatingHint;
import com.codename1.components.ToastBar;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.io.rest.Response;
import com.codename1.io.rest.Rest;
import com.codename1.ui.Button;
import com.codename1.ui.ButtonGroup;
import com.codename1.ui.Container;
import com.codename1.ui.RadioButton;
import com.codename1.ui.TextField;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.events.ActionListener;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.GridLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.mycompany.entities.Candidat;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class SignIn extends BaseForm {
    public static Candidat candidat = new Candidat();
    int type=0;
    public SignIn(Resources res) {
        super(new BorderLayout());
        
        if(!Display.getInstance().isTablet()) {
            BorderLayout bl = (BorderLayout)getLayout();
            bl.defineLandscapeSwap(BorderLayout.NORTH, BorderLayout.EAST);
            bl.defineLandscapeSwap(BorderLayout.SOUTH, BorderLayout.CENTER);
        }
        getTitleArea().setUIID("Container");
        setUIID("SignIn");
        
        add(BorderLayout.NORTH, new Label(res.getImage("Logo.png"), "LogoLabel"));
        
        TextField username = new TextField("", "Username", 20, TextField.ANY);
        TextField password = new TextField("", "Password", 20, TextField.PASSWORD);
        username.setSingleLineTextArea(false);
        password.setSingleLineTextArea(false);
        Button signIn = new Button("Sign In");
        //Button signUp = new Button("Sign Up");
        //signUp.addActionListener(e -> new SignUpForm(res).show());
        //signUp.setUIID("Link");
        //Label doneHaveAnAccount = new Label("Don't have an account?");
        ButtonGroup barGroup = new ButtonGroup();
        RadioButton all = RadioButton.createToggle("Condidat", barGroup);
        all.setSelected(true);
        RadioButton featured = RadioButton.createToggle("Moniteur", barGroup);
        all.setUIID("Button");
        featured.setUIID("Button");

        //Container bg = new Container(new FlowLayout(CENTER,barGroup));
        Container content = BoxLayout.encloseY(
                new FloatingHint(username),
                createLineSeparator(),
                new FloatingHint(password),
                createLineSeparator(),
                signIn
                //,createLineSeparator(),LayeredLayout.encloseIn( GridLayout.encloseIn(2, all, featured))
                //FlowLayout.encloseCenter(doneHaveAnAccount, signUp)
        );
        
//        barGroup.addActionListener((evt) -> {
//               switch(barGroup.getSelectedIndex()){
//                    case (0):{
//                      
//                        type=0; break;
//                    }
//                    case (1):{
//                        type=1;
//                                System.out.println("mon selected");
//                                break;
//                    }
//                    
//                }
//       
//           
//        });
        content.setScrollableY(true);
        add(BorderLayout.SOUTH, content);
        signIn.requestFocus();
        // Rest GET Login
        signIn.addActionListener((ActionListener) (ActionEvent evt) -> {
            String email = username.getText();
            String pass = password.getText();
            Response<Map> resultData = Rest.get("http://localhost/pirania/web/app_dev.php/ws/login/"+email+"/"+pass+"/0").acceptJson().getAsJsonMap();
            
            if(resultData.getResponseCode() != 200) {
                callSerially(() -> {
                    ToastBar.showErrorMessage("Vérifier votre email ou mot de passe\n");
                });
            }
            else{
                String nom = (String)resultData.getResponseData().get("nom");
                String prenom = (String)resultData.getResponseData().get("prenom");
                String cin = (String)resultData.getResponseData().get("cin");
                Double iddouble =(Double)resultData.getResponseData().get("id");
                candidat.setEmail(email);
                candidat.setNom(nom);
                candidat.setCin(cin);
                candidat.setId(iddouble.intValue());
                candidat.setPrenom(prenom);
                candidat.setMotdepasse(pass);
                System.out.println(candidat);
                new NewsfeedForm(res).show();
            }
        });
    }
}
